### ISSUE TITLE
another text editor

### ISSUE THREAD

**Issue by Alexey-T** [Ta2i4/BirEdit#6]
Hello. уже существует мой CudaText, open src, так что возможно вам не стОит тратить силы, на новый проект.

**Comment by Alexey-T** [comment]
к тому же, ваш на SynEdit, что делает много ограничений (под Лазарус synedit даже не умеет word wrap, мало поддерживает multi carets, и много чего еще).

**Comment by Ta2i4** [comment]
> Hello. уже существует мой CudaText, open src, так что возможно вам не стОит тратить силы, на новый проект.

Добрый день! BirEdit - это старый проект, которому более 10 лет. Наконец-то выложил его на github :)

**Comment by Ta2i4** [comment]
> к тому же, ваш на SynEdit, что делает много ограничений (под Лазарус synedit даже не умеет word wrap, мало поддерживает multi carets, и много чего еще).

Я не планировал проверять код на совместимость с Lazarus
